config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'
    # , registrations: 'users/registrations'
  }

  resources :users
  resources :teachers, only: [:index, :show, :edit, :update] do
    resources :students, only: [:index, :show, :new, :create]
  end

  resources :students do
    resources :pledges, only: [:new, :create, :show , :index]
  end

  resources :students, only: [:index, :show, :edit, :update]
  resources :comments, only: [:new, :create]
  resources :pledges, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: "static#home"

 get '/auth/facebook/callback' => 'sessions#create'

 get 'most_pledges', to: 'pledges#most_pledges'
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :students
  belongs_to :user


# Possible feature to find total pledges made by teachers students
# def student_pledge_total
#   self.students.pledges.sum(:amount)
# end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
      @teachers = Teacher.all
       
      render json: @teachers
    # respond_to do |format|
    #   format.html { render :index }
    #   format.json { render json: @teachers }
    # end
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    if params[:student_ids] != nil
       params[:student_ids].each do |student_id|
          student = Student.find(student_id)
          student.teacher_id = params[:id]

          student.save
          redirect_to teacher_path(params[:id])
       end
    else
      redirect_to teacher_path(params[:id])
    end
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<h1> Add a student to your class: </h1>

<%= form_for @teacher, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
  <% Student.all.where("teacher_id != ?", params[:id]).each do |student| %>
    <p><%= check_box_tag 'student_ids[]', student.id %>
      Student Name: <%= student.last_name%>, <%= student.first_name %>,
       Current Teacher: <%=student.teacher.last_name %>
    </p>
  <% end %>
    <%= f.submit "Add Student" %>
<% end %>

<h1> Current Students: </h1>
<% Student.all.where("teacher_id = ?", params[:id]).each do |student| %>

  <li><%= student.last_name%>, <%= student.first_name %></li>
<% end %>

app/views/teachers/show.html.erb
<div id="main">
  <div class="leftcolumnteacher">
  <%= @teacher.first_name %> <%= @teacher.last_name %>'s  Class
    <% @teacher.students.each do |s| %>
    <div class= 'student_box'>

        <%= s.first_name %> <%= s.last_name %>
        <%= button_to "Students Profile", teacher_student_path(@teacher ,s), {method: 'get', class: "some-class"} %>
      </div>
    <% end %>
     <% if current_user != nil && current_user.id == @teacher.user_id   %>
         <%= link_to "Add Student", edit_teacher_path(@teacher) %>
         <%= link_to "Add New Student",  new_teacher_student_path(@teacher) %>
     <% end %>
  </div>

  <div class="rightcolumnteacher">

    <div class="studentinfo">

    </div>
    <div class="pledge_form">
    </div>
  </div>

</div>

<script id="student-template" type="text/x-handlebars-template">
    <h1> Student {{first_name}} {{last_name}}  Details </h1>

      <!--HOw do I refactor for handle bar template  -->
    <!-- < if current_user == @student >
      <=  button_to "Edit Profile" > -->
    <!-- < end %> -->
    <p> Charities  Raising money for and current amount<p>

    <div class = "student_section">
        <a href=`/students/{{id}}` class ="pledge-sort"> Sort Pledges</a>
      <div class = "boxes">
        {{#each charities}}
        <!-- NEED ACCESS TO THIS CHARITY ID for new PLedge form and controller -->
        <!-- {{id}} -->
          <div class= "charity_box">
            {{name}}
            <p>{{description}}</p>
        {{/each}}
          </div>
          <!-- <p> Goal:</p> -->
          <!-- MAy need to chang this for matching amount to each charity of student  -->
          <!-- <p> Amount Pledged:</p> -->
          <!-- How to refactor for handlebars? -->
          <!-- $<= @student.amount_pledged() %> -->

          <div class="comments_section">


           {{#each pledges}}
              <p>Amount: ${{amount}}</p>
                <!-- Need pledge.comments -->
              {{#each comments}}
                  <p>Comment: {{content}}</p>
              {{/each}}
            {{/each}}
          <div class="newest_pledge" >
            <!-- div for inserting newsest pledge via JS  -->
          </div>
        </div>
        </div>
      </div>
</script>